"use client";
import { FormEvent,useMemo,useState } from "react";
const steps=[
{key:"service",title:"What are you planning?",options:["OOH / DOOH","Experiential","Retail Media","Digital Marketing","Production"]},
{key:"market",title:"Which market or markets?",options:["Miami","New York","Los Angeles","Toronto","Multiple Markets"]},
{key:"budget",title:"Estimated budget?",options:["Under $25K","$25K–$75K","$75K–$150K","$150K+"]},
{key:"timing",title:"Campaign timing?",options:["ASAP","Within 30 days","1–3 months","Still planning"]}];
export default function CampaignAssistant(){
const[open,setOpen]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[sent,setSent]=useState(false),[sending,setSending]=useState(false);
const current=steps[step],complete=step>=steps.length,summary=useMemo(()=>Object.entries(answers).map(([k,v])=>`${k}: ${v}`).join(" | "),[answers]);
function choose(v:string){setAnswers(p=>({...p,[current.key]:v}));setStep(p=>p+1)}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);const f=new FormData(e.currentTarget);const payload={name:f.get("name"),company:f.get("company"),email:f.get("email"),phone:f.get("phone"),notes:f.get("notes"),answers};const r=await fetch('/api/brief',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setSending(false);if(r.ok)setSent(true)}
function reset(){setStep(0);setAnswers({});setSent(false)}
return <><button className="assistantTrigger" onClick={()=>setOpen(true)}><span className="assistantDot"/>Plan a Campaign</button>{open&&<div className="assistantOverlay"><div className="assistantPanel"><button className="assistantClose" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">NORTH POINT CAMPAIGN ASSISTANT</p>{!complete?<><h3>{current.title}</h3><div className="assistantOptions">{current.options.map(o=><button key={o} onClick={()=>choose(o)}>{o}</button>)}</div></>:sent?<><h3>Thank you. Your request has been received.</h3><p className="assistantSummary">We will review your preliminary brief and follow up using the contact details provided.</p><button className="primary" onClick={()=>setOpen(false)}>Close</button><button className="assistantReset" onClick={reset}>Submit another request</button></>:<><h3>Your preliminary brief is ready.</h3><p className="assistantSummary">{summary}</p><form className="briefForm" onSubmit={submit}><div className="briefTwoCol"><input required name="name" placeholder="Name *"/><input name="company" placeholder="Company"/><input required type="email" name="email" placeholder="Email *"/><input name="phone" placeholder="Phone"/></div><textarea name="notes" placeholder="Anything else we should know?" rows={4}/><button className="primary" disabled={sending}>{sending?'Sending...':'Submit Request'}</button></form><button className="assistantReset" onClick={reset}>Start again</button></>}</div></div>}</>}
